#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo -ne "$2") > /dev/null
}

case "$1" in
    1)  
        assert-equal "./test 7 2" '2\n'
        ;;
    2)  
        assert-equal "./test 5 -4" '-1\n'
        ;;
    3)  
        assert-equal "./test 5 6" '-1\n'
        ;;
    4)  
        assert-equal "./test 8 100" '-1\n'
        ;;
    5)  
        assert-equal "./test 10 10" '-1\n'
        ;;
    6)  
        assert-equal "./test 15 8" '8\n'
        ;;
    7)  
        assert-equal "./test -20 5" '-1\n'
        ;;
    8)  
        assert-equal "./test -1 11" '-1\n'
        ;;
esac